Better error message when bit pattern is missing.
Previously;
```
    self.apply_directive('buffer', src, dst)
  File "/usr/local/google/home/tansell/work/catx/vtr/env/conda/bin/icebox_hlc2asc", line 698, in apply_directive
    bits, = [entry[0] for entry in self.db if entry[1:] == fields]
ValueError: not enough values to unpack (expected 1, got 0)
```

Now:
```
Parse error in line 2108:
    span12_y4_g14_0 -> span4_y4_g11_7 <-> span4_x7_g4_0

No bit pattern for ['buffer', 'sp12_h_r_11', 'sp4_h_r_7'] in LogicTile(1k, 7, 4)
```